import { Globe, Share2, Users } from 'lucide-react';

export const streamingPlatforms = [
  {
    id: 1,
    name: 'Spotify',
    followers: '12.5K',
    monthlyListeners: '45.2K',
    url: 'https://open.spotify.com/artist/4GIlGL9p0s5IgGFu212QUS?si=6-KHEpmPQ3mTHwnLdw2iDg',
    color: '#1DB954',
    description: 'Main catalog and playlists',
    verified: true,
  },
  {
    id: 2,
    name: 'Apple Music',
    followers: '8.3K',
    monthlyListeners: '32.1K',
    url: 'https://music.apple.com/artist/linarex',
    color: '#FA243C',
    description: 'High-quality streaming',
    verified: true,
  },
  {
    id: 3,
    name: 'YouTube Music',
    followers: '15.7K',
    monthlyListeners: '78.4K',
    url: 'https://music.youtube.com/watch?v=sGx7yOn5fN8&si=QrHm7pE5_rczX42-',
    color: '#FF0000',
    description: 'Music videos and live sessions',
    verified: true,
  },
  // {
  //   id: 4,
  //   name: 'SoundCloud',
  //   followers: '9.2K',
  //   monthlyListeners: '28.9K',
  //   url: 'https://soundcloud.com/linarex',
  //   color: '#FF5500',
  //   description: 'Demos and exclusive content',
  //   verified: false,
  // },
  // {
  //   id: 5,
  //   name: 'Bandcamp',
  //   followers: '3.1K',
  //   monthlyListeners: '12.4K',
  //   url: 'https://linarex.bandcamp.com',
  //   color: '#1DA0C3',
  //   description: 'Direct artist support',
  //   verified: true,
  // },
  // {
  //   id: 6,
  //   name: 'Amazon Music',
  //   followers: '5.8K',
  //   monthlyListeners: '21.3K',
  //   url: 'https://music.amazon.com/artists/linarex',
  //   color: '#FF9900',
  //   description: 'HD and Ultra HD quality',
  //   verified: true,
  // },
];

export const socialPlatforms = [
  {
    id: 1,
    name: 'Instagram',
    handle: '@linarex_official',
    followers: '18.4K',
    url: 'https://instagram.com/linarex_official',
    color: '#E4405F',
    type: 'photo',
    description: 'Behind the scenes, studio life',
  },
  // {
  //   id: 2,
  //   name: 'Twitter/X',
  //   handle: '@linarex_music',
  //   followers: '12.7K',
  //   url: 'https://x.com/linarex_music',
  //   color: '#000000',
  //   type: 'text',
  //   description: 'Updates, thoughts, industry news',
  // },
  // {
  //   id: 3,
  //   name: 'Facebook',
  //   handle: '/LinarexOfficial',
  //   followers: '9.3K',
  //   url: 'https://facebook.com/LinarexOfficial',
  //   color: '#1877F2',
  //   type: 'community',
  //   description: 'Community and event updates',
  // },
  {
    id: 4,
    name: 'TikTok',
    handle: '@linarexmusic',
    followers: '25.1K',
    url: 'https://tiktok.com/@linarexmusic',
    color: '#000000',
    type: 'video',
    description: 'Short-form content, music clips',
  },
  // {
  //   id: 5,
  //   name: 'LinkedIn',
  //   handle: '/in/linarex-producer',
  //   followers: '4.2K',
  //   url: 'https://linkedin.com/in/linarex-producer',
  //   color: '#0A66C2',
  //   type: 'professional',
  //   description: 'Industry connections, collaborations',
  // },
  // {
  //   id: 6,
  //   name: 'Discord',
  //   handle: 'Linarex Community',
  //   followers: '1.8K',
  //   url: 'https://discord.gg/linarex',
  //   color: '#5865F2',
  //   type: 'community',
  //   description: 'Direct fan interaction, exclusives',
  // },
];

export const officialLinks = [
  {
    id: 1,
    name: 'Official Website',
    url: 'https://linarex-music.com',
    description: 'Main hub for all content and updates',
    icon: Globe,
  },
  {
    id: 2,
    name: 'Booking & Management',
    url: 'mailto:booking@linarex-music.com',
    description: 'Professional inquiries and booking',
    icon: Users,
  },
  {
    id: 3,
    name: 'Press Kit',
    url: '#media-kit',
    description: 'Media assets and press materials',
    icon: Share2,
  },
];
