export const upcomingShows = [
  {
    id: 1,
    date: '2024-02-15',
    venue: 'Metal Underground',
    city: 'Berlin',
    country: 'Germany',
    type: 'Headline Show',
    status: 'confirmed',
    ticketLink: '#',
  },
  {
    id: 2,
    date: '2024-03-08',
    venue: 'Progressive Night',
    city: 'Amsterdam',
    country: 'Netherlands',
    type: 'Festival',
    status: 'confirmed',
    ticketLink: '#',
  },
  {
    id: 3,
    date: '2024-03-22',
    venue: 'Rock Palace',
    city: 'Madrid',
    country: 'Spain',
    type: 'Support Act',
    status: 'pending',
    ticketLink: '#',
  },
];

export const photoGallery = [
  {
    id: 6,
    src: 'https://res.cloudinary.com/freelancer2222222222222222/image/upload/v1771093990/linarex/black_un2msx.jpg',
    venue: 'There is a melody in every shadow.',
    location: 'Warsaw, Poland ',
    photographer: 'Yuki Tanaka',
  },
  {
    id: 1,
    src: '/img/Singin.png',
    venue: 'Found joy in the simplest moments.',
    location: 'Santo Domingo, DR',
    photographer: 'Anna Rodriguez',
  },
  {
    id: 2,
    src: 'https://res.cloudinary.com/freelancer2222222222222222/image/upload/v1780170735/linarex/standing_wicdur.jpg',
    venue: 'Profile of a dreamer.',
    location: 'Kraków, Poland',
    photographer: 'Hans Mueller',
  },
  {
    id: 3,
    src: 'https://res.cloudinary.com/freelancer2222222222222222/image/upload/v1780170739/linarex/trenes_lj3rfh.jpg',

    venue: 'Six strings and good vibes.',
    location: 'Warsaw, Poland',
    photographer: 'Adiel Zarco',
  },
  {
    id: 4,
    src: '/img/train.jpg',
    venue: 'Hotel Atlantis',
    location: 'Dubai, UAE',
    photographer: 'Sarah Al-Zahra',
  },
  {
    id: 5,
    src: '/img/DSC00047.jpg',
    venue: 'Jazz & Metal Fusion',
    location: 'New York, USA',
    photographer: 'Mike Johnson',
  },
  {
    id: 5,
    src: '/img/perfil-2.jpg',
    venue: 'Jazz & Metal Fusion',
    location: 'New York, USA',
    photographer: 'Mike Johnson',
  },
];
